on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Login to Docker registry
      - name: 'Login to Docker registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push Docker image
      - name: 'Build and push Docker image'
        run: |
          printenv PAYLOAD_SECRET
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/esf-web:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/esf-web:${{ github.sha }}
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
